
class Config:
    INPUT_DEVICE_INDEX = 1

    LEFT_MIC_INDEX = 2
    RIGHT_MIC_INDEX = 1

    OUTPUT_DEVICE_INDEX = 8
    SAMPLERATE = 16000
    AUDIO_CHUNK_MS = 70

    AUDIO_PLAYBACK_DELAY_S = 2
    VIBRATION_DELAY_S = 2

    VIB_OUT_SCALE = 20
    HVIB_OUT_SCALE = 1

    HEAT_TIME = 1.5
    THERM_OUT_SCALE = 1

    
    MIMIC_STEREO = True